### ISSUE TITLE
Allow urls with `wss` scheme

### ISSUE THREAD

**Issue by jisaacstone** [jacksonofalltrades/pydeepstream#2]
in `interface.py` around line 87 there is an `if parse_result.scheme == 'ws'`

Should also allow `wss`

**Comment by sapid** [comment]
https://github.com/jacksonofalltrades/pydeepstream/blob/master/deepstreampy_twisted/interface.py#L56

This is the only mention of `parse_result.scheme` in `interface.py` and it already accepts `wss`. This is also not particularly close to line 87 - are you looking at a different file?

**Comment by sapid** [comment]
Ah, my bad, @jacksonofalltrades snuck in a commit and didn't mention it in this issue. :) Fixed in [ce84e1e](https://github.com/jacksonofalltrades/pydeepstream/commit/ce84e1eba8d8f11b9d966491683ee61c89ba467c) but probably untested.

**Comment by jacksonofalltrades** [comment]
We tested it at Nimble, it works!

**Comment by sapid** [comment]
Great!
