### ISSUE TITLE
should default connection string to 'ssl:' if shceme is 'wss:'

### ISSUE THREAD

**Issue by jisaacstone** [jacksonofalltrades/pydeepstream#5]
https://github.com/jacksonofalltrades/pydeepstream/blob/master/deepstreampy_twisted/interface.py#L58

I'm passing in the conn_string manually as a workaround for now

**Comment by jacksonofalltrades** [comment]
@jisaacstone When do you need this by? Next week ok?

**Comment by jisaacstone** [comment]
sure yeah that works
